### ISSUE TITLE
Download images on the fly through MediaMock

### ISSUE THREAD

**Issue by peterjaap** [SchumacherFM/mediamock#10]
I'd love to see an option where MediaMock does download the images from the production server and shows them, instead of generating random images.

It kinda defeats the purpose, but I'd like to see the actual images and not have to download images for 90k products but download them as we go. Maybe add an optional argument to the server like --download-images and add an argument like --download-dir to point to a directory where they should be saved to (and retrieved from).

**Comment by SchumacherFM** [comment]
What should happen when an image does not exists on the remote server?

Should the downloaded images be cached on your dev machine? Where? Or should mediamock download them for every request? 

Would you like to map the whole media directory to the remote server or only subfolders and let the other folders be generated?!

For the on-the-fly download you can install https://github.com/SchumacherFM/mediamock-magento and change the `media_url` in the `core_config_data` table to the remote server. This only works as long as you have internet connection. With mediamock you can work offline.

**Comment by peterjaap** [comment]
- Then a random image should be generated
- Yes, in the /media dir or in another dir if the --download-dir (or --cache-dir or whatever) is given
- The whole media dir

**Comment by SchumacherFM** [comment]
If you are interested in learning Go I can provide you with the needed empty functions and the failing tests then it would be your task to create the fully working functions to pass the tests. Let me know :-)

**Comment by SchumacherFM** [comment]
Fixed

See https://github.com/SchumacherFM/mediamock/releases/tag/v0.6.0

Please try it out and report any bugs in a new issue!
